language: ruby
rvm:
  - 2.2

bundler_args: --without development

before_script:
  - cp config/secrets.template.yml config/secrets.yml

script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rspec spec